version: '3.7'

services:
    http:
        container_name: http
        image: nginx:alpine
        volumes:
            - ./code:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80

    php:
        container_name: php
        build: .
        expose:
            - 9000
        volumes:
            - ./code:/app
