version: '3.7'

services:
    http:
        container_name: http
        image: nginx:alpine
        volumes:
            - ./code:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80

    php:
        container_name: php
        build: .
        expose:
            - 9000
        volumes:
            - ./code:/app

    mongo:
        container_name: mongo
        image: mongo:4.2-rc-bionic
        restart: always
        ports:
            - 27017:27017
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: root
        #     MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            # ME_CONFIG_MONGODB_ADMINUSERNAME: root
            # ME_CONFIG_MONGODB_ADMINPASSWORD: example